// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FinanceBetterTrading.Test.ServiceTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class StockPriceServiceTestsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "StockPriceServiceTests.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "StockPriceServiceTests", "In order to avoid silly mistakes\nAs a math idiot\nI want to be told the sum of two" +
                    " numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "StockPriceServiceTests")))
            {
                FinanceBetterTrading.Test.ServiceTests.StockPriceServiceTestsFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("依照股票Code，來尋找出該支股票")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "StockPriceServiceTests")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        public virtual void 依照股票Code來尋找出該支股票()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("依照股票Code，來尋找出該支股票", new string[] {
                        "mytag"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("查詢條件股票代號為 0001", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Code",
                        "Date",
                        "OpenPrice",
                        "ClosePrice",
                        "HeightPrice",
                        "LowerPrice",
                        "Volumn",
                        "TradeAmount",
                        "TradeShare"});
            table1.AddRow(new string[] {
                        "Test",
                        "0001",
                        "103/10/01",
                        "26.50",
                        "26.50",
                        "26.50",
                        "26.50",
                        "100",
                        "100",
                        "100"});
            table1.AddRow(new string[] {
                        "Test",
                        "0001",
                        "103/10/02",
                        "26.50",
                        "26.50",
                        "26.50",
                        "26.50",
                        "100",
                        "100",
                        "100"});
            table1.AddRow(new string[] {
                        "Test",
                        "0001",
                        "103/10/03",
                        "26.50",
                        "26.50",
                        "26.50",
                        "26.50",
                        "100",
                        "100",
                        "100"});
            table1.AddRow(new string[] {
                        "Test",
                        "0001",
                        "103/10/04",
                        "26.50",
                        "26.50",
                        "26.50",
                        "26.50",
                        "100",
                        "100",
                        "100"});
#line 9
 testRunner.And("預計stockprice資料表應有", ((string)(null)), table1, "And ");
#line 15
 testRunner.When("呼叫查詢結果", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Code",
                        "Date",
                        "OpenPrice",
                        "ClosePrice",
                        "HeightPrice",
                        "LowerPrice",
                        "Volumn",
                        "TradeAmount",
                        "TradeShare"});
            table2.AddRow(new string[] {
                        "Test",
                        "0001",
                        "103/10/01",
                        "26.50",
                        "26.50",
                        "26.50",
                        "26.50",
                        "100",
                        "100",
                        "100"});
            table2.AddRow(new string[] {
                        "Test",
                        "0001",
                        "103/10/02",
                        "26.50",
                        "26.50",
                        "26.50",
                        "26.50",
                        "100",
                        "100",
                        "100"});
            table2.AddRow(new string[] {
                        "Test",
                        "0001",
                        "103/10/03",
                        "26.50",
                        "26.50",
                        "26.50",
                        "26.50",
                        "100",
                        "100",
                        "100"});
            table2.AddRow(new string[] {
                        "Test",
                        "0001",
                        "103/10/04",
                        "26.50",
                        "26.50",
                        "26.50",
                        "26.50",
                        "100",
                        "100",
                        "100"});
#line 16
 testRunner.Then("查詢結果應為", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
